### PR TITLE
Arxiv scraping is done

### PR DESCRIPTION
**Pull request by lukas-varga**
Arxiv scraping is done, not yet implemented in the way of orchestrator, cause it has some differences in comparison to YT and Podcast, but fully working similarly to pubmed. Python API arxiv used while development.

### CODE REVIEW

**Comment by eloinoel** [comment]
Wow, I am impressed, how fast this went. Looks very good. One small question: In pubmed it was possible to filter out any non free papers, maybe this is also possible here? Or maybe all papers are free on arxiv, I actually don't know.

**Comment by lukas-varga** [comment]
Yeah I tried total focus mode during afternoon till midnight xD. I read and have the same opinion by looking at Arxiv, there since its open source there are no paid articles there. At least Arxiv doesnt support that. Also in pubmed you search for all keywords at once, in Arxiv this doesnt seems to work so well so I scraped every keyword separetly/

**Comment by lukas-varga** [comment]
> Wow, I am impressed, how fast this went. Looks very good. One small question: In pubmed it was possible to filter out any non free papers, maybe this is also possible here? Or maybe all papers are free on arxiv, I actually don't know.

Yeah I tried total focus mode during afternoon till midnight xD. I read and have the same opinion by looking at Arxiv, there since its open source there are no paid articles there. At least Arxiv doesnt support that. Also in pubmed you search for all keywords at once, in Arxiv this doesnt seems to work so well so I scraped every keyword separetly.

**Review by eloinoel — APPROVED** [review]
Alright, then I think this is ready for merge

**Pull request merged**
