### PR TITLE
Podcast scrapper refactored (orchestrator)

### PR DESCRIPTION
**Pull request by lukas-varga**
refactored using new orchestrator methods, also added downloading zip of vosk

### CODE REVIEW

**Comment by preetvadaliya** [comment]
@lukas-varga its good but it would be good if you make your PR title small, its breaking.

**Comment by lukas-varga** [comment]
> @lukas-varga its good but it would be good if you make your PR title small, its breaking.

Okay next time I will, It just take the last commut message

**Review by preetvadaliya — APPROVED** [review]

**Comment by preetvadaliya** [comment]
@lukas-varga , its looks good to merge, the workflow is failed don't worry about that, I have removed the dependency of external bot from repository so first we have to merge open PR #104 then we will re-run this. if you can approve then we can merge these two PR today.

Best,
Preet

**Comment by lukas-varga** [comment]
> @lukas-varga , its looks good to merge, the workflow is failed don't worry about that, I have removed the dependency of external bot from repository so first we have to merge open PR #104 then we will re-run this. if you can approve then we can merge these two PR today.
> 
> Best, Preet

Yeah I have reviewed and merged #104

**Pull request merged**
