### PR TITLE
Reorganised directory structure

### PR DESCRIPTION
**Pull request by eloinoel**
….enescu@fau.de>

### CODE REVIEW

**Comment by preetvadaliya** [comment]
@eloinoel , @EnescuDavid 

This looks good but I want to say can we move everything inside `src/backend` because in future there will be code for frontend as well so.

Best,
Preet

**Comment by EnescuDavid** [comment]
Everything is already in src/backend or what do you mean exactly?

**Review by EnescuDavid — APPROVED** [review]

**Comment by eloinoel** [comment]
Right now we have named the directories according to the architecture diagram (https://www.figma.com/file/xw3BjIrXL79BjpTK57RRRq/System-Architecture?type=whiteboard&node-id=0-1&t=aG9QyUQwAWkxgeIw-0).
So it would be src/data_pipeline/... but you can also structure into frontend and backend, I don't mind. Just need to settle on one thing.

**Comment by preetvadaliya** [comment]
can we do something like this?

```
.
├── backend
│   ├── data_acquisition
│   │   ├── config.json
│   │   ├── config.py
│   │   ├── orchestrator.py
│   │   ├── scrapers
│   │   │   ├── podcast
│   │   │   │   ├── podcast_scraping.py
│   │   │   │   ├── podcast_text_20240507_191423.json
│   │   │   │   ├── vosk-model-small-en-us-0.15
│   │   │   │   │   ├── am
│   │   │   │   │   │   └── final.mdl
│   │   │   │   │   ├── conf
│   │   │   │   │   │   ├── mfcc.conf
│   │   │   │   │   │   └── model.conf
│   │   │   │   │   ├── graph
│   │   │   │   │   │   ├── disambig_tid.int
│   │   │   │   │   │   ├── Gr.fst
│   │   │   │   │   │   ├── HCLr.fst
│   │   │   │   │   │   └── phones
│   │   │   │   │   │       └── word_boundary.int
│   │   │   │   │   ├── ivector
│   │   │   │   │   │   ├── final.dubm
│   │   │   │   │   │   ├── final.ie
│   │   │   │   │   │   ├── final.mat
│   │   │   │   │   │   ├── global_cmvn.stats
│   │   │   │   │   │   ├── online_cmvn.conf
│   │   │   │   │   │   └── splice.conf
│   │   │   │   │   └── README
│   │   │   │   └── vosk-model-small-en-us-0.15.zip
│   │   │   └── youtube
│   │   │       ├── index.py
│   │   │       ├── __init__.py
│   │   │       └── you_tube.py
│   │   └── utils
│   │       ├── file_utils.py
│   │       └── __init__.py
│   └── rag
└── frontend
```

**Comment by eloinoel** [comment]
Yeah looks good. How did you generate this diagram? Looks really nice ;)

**Comment by eloinoel** [comment]
Changed it. Should be ready for merge now. @preetvadaliya

**Comment by preetvadaliya** [comment]
LGTM

**Pull request merged**
