### PR TITLE
Podcast scraper fixes (code cleaning & deleting audio raw files)

### PR DESCRIPTION
**Pull request by lukas-varga**
Those fixes should be already merged on main, but apparently it got lost somewhere when we tried to cherry-pick commits with Preet last week. I added removing podcast audio raw files after transcription because Andi said, he needs only text. A bit of code cleaning as well, everythings works fine.
LV

### CODE REVIEW

**Review by eloinoel — APPROVED** [review]
Should be ready for merge to main branch. I pasted the code to the Scraper/PodCast/ folder. It will have to be integrated into the pipeline and deleted next sprint.

@preetvadaliya Review that what I have done is correct, when you have time. Thanks :)

**Comment by lukas-varga** [comment]
> Should be ready for merge to main branch. I pasted the code to the Scraper/PodCast/ folder. It will have to be integrated into the pipeline and deleted next sprint.
> 
> @preetvadaliya Review that what I have done is correct, when you have time. Thanks :)

Okay thanks @eloinoel so all the changes are now aligned with the new structure

**Comment by preetvadaliya** [comment]
@eloinoel , @lukas-varga  its looks good in next sprint we will refactor it. I have to merge main branch again in this once i am done with this you can merge this.

**Comment by preetvadaliya** [comment]
meanwhile making it draft

**Review by preetvadaliya — APPROVED** [review]

**Pull request merged**
